//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShareResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShareResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineExaminationSystem.Web.Resources.ShareResources", typeof(ShareResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 增加.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统出错，请重试！.
        /// </summary>
        public static string An_unexpected_error_has_occurred__please_try_again_ {
            get {
                return ResourceManager.GetString("An unexpected error has occurred, please try again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭全部选项卡.
        /// </summary>
        public static string Close_All_Tabs {
            get {
                return ResourceManager.GetString("Close All Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭其他选项卡.
        /// </summary>
        public static string Close_Other_Tabs {
            get {
                return ResourceManager.GetString("Close Other Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加时间.
        /// </summary>
        public static string Create_Time {
            get {
                return ResourceManager.GetString("Create Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 考试管理.
        /// </summary>
        public static string Examination_Management {
            get {
                return ResourceManager.GetString("Examination Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定位当前选项卡.
        /// </summary>
        public static string Lock_Current_Tab {
            get {
                return ResourceManager.GetString("Lock Current Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线考试.
        /// </summary>
        public static string Online_Examination {
            get {
                return ResourceManager.GetString("Online Examination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭操作.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试卷列表.
        /// </summary>
        public static string Paper_List {
            get {
                return ResourceManager.GetString("Paper List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试卷规则.
        /// </summary>
        public static string Paper_Rules {
            get {
                return ResourceManager.GetString("Paper Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择一条记录！.
        /// </summary>
        public static string Please_select_one_record {
            get {
                return ResourceManager.GetString("Please select one record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 题目列表.
        /// </summary>
        public static string Question_List {
            get {
                return ResourceManager.GetString("Question List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 题库管理.
        /// </summary>
        public static string Questions_Management {
            get {
                return ResourceManager.GetString("Questions Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课程.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 科目列表.
        /// </summary>
        public static string Subject_List {
            get {
                return ResourceManager.GetString("Subject List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交成功.
        /// </summary>
        public static string Submit_Success {
            get {
                return ResourceManager.GetString("Submit Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标题.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新时间.
        /// </summary>
        public static string Update_Time {
            get {
                return ResourceManager.GetString("Update Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户列表.
        /// </summary>
        public static string User_List {
            get {
                return ResourceManager.GetString("User List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户管理.
        /// </summary>
        public static string User_Management {
            get {
                return ResourceManager.GetString("User Management", resourceCulture);
            }
        }
    }
}
