//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShareResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShareResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineExaminationSystem.Web.Resources.ShareResources", typeof(ShareResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 增加.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统出错，请重试！.
        /// </summary>
        public static string An_unexpected_error_has_occurred__please_try_again_ {
            get {
                return ResourceManager.GetString("An unexpected error has occurred, please try again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 答案.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注: 多个项以|分隔.
        /// </summary>
        public static string Answer_Note {
            get {
                return ResourceManager.GetString("Answer Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择题.
        /// </summary>
        public static string Choice {
            get {
                return ResourceManager.GetString("Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择题数量.
        /// </summary>
        public static string Choice_Count {
            get {
                return ResourceManager.GetString("Choice Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭全部选项卡.
        /// </summary>
        public static string Close_All_Tabs {
            get {
                return ResourceManager.GetString("Close All Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭其他选项卡.
        /// </summary>
        public static string Close_Other_Tabs {
            get {
                return ResourceManager.GetString("Close Other Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加时间.
        /// </summary>
        public static string Create_Time {
            get {
                return ResourceManager.GetString("Create Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 难度.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 考试管理.
        /// </summary>
        public static string Examination_Management {
            get {
                return ResourceManager.GetString("Examination Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 考试时长.
        /// </summary>
        public static string Examination_Time {
            get {
                return ResourceManager.GetString("Examination Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请完成所有项的输入.
        /// </summary>
        public static string Fields_Required {
            get {
                return ResourceManager.GetString("Fields Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 填空题.
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 填空题数量.
        /// </summary>
        public static string Fill_Count {
            get {
                return ResourceManager.GetString("Fill Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注：填空题空格用（）表示.
        /// </summary>
        public static string Fill_Note {
            get {
                return ResourceManager.GetString("Fill Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 判断题.
        /// </summary>
        public static string Judgment {
            get {
                return ResourceManager.GetString("Judgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 判断题数量.
        /// </summary>
        public static string Judgment_Count {
            get {
                return ResourceManager.GetString("Judgment Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定位当前选项卡.
        /// </summary>
        public static string Lock_Current_Tab {
            get {
                return ResourceManager.GetString("Lock Current Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手动添加.
        /// </summary>
        public static string Mannual_Add {
            get {
                return ResourceManager.GetString("Mannual Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线考试.
        /// </summary>
        public static string Online_Examination {
            get {
                return ResourceManager.GetString("Online Examination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项A .
        /// </summary>
        public static string Option_A {
            get {
                return ResourceManager.GetString("Option A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项B.
        /// </summary>
        public static string Option_B {
            get {
                return ResourceManager.GetString("Option B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项C.
        /// </summary>
        public static string Option_C {
            get {
                return ResourceManager.GetString("Option C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项D.
        /// </summary>
        public static string Option_D {
            get {
                return ResourceManager.GetString("Option D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭操作.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试卷.
        /// </summary>
        public static string Paper {
            get {
                return ResourceManager.GetString("Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试卷列表.
        /// </summary>
        public static string Paper_List {
            get {
                return ResourceManager.GetString("Paper List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试卷规则.
        /// </summary>
        public static string Paper_Rules {
            get {
                return ResourceManager.GetString("Paper Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择一条记录！.
        /// </summary>
        public static string Please_select_one_record {
            get {
                return ResourceManager.GetString("Please select one record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 问答题.
        /// </summary>
        public static string Q_A {
            get {
                return ResourceManager.GetString("Q&A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 问答题数量.
        /// </summary>
        public static string Q_A_Count {
            get {
                return ResourceManager.GetString("Q&A Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 题目.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 题干.
        /// </summary>
        public static string Question_Content {
            get {
                return ResourceManager.GetString("Question Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 题库.
        /// </summary>
        public static string Question_List {
            get {
                return ResourceManager.GetString("Question List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 题库管理.
        /// </summary>
        public static string Questions_Management {
            get {
                return ResourceManager.GetString("Questions Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 题型.
        /// </summary>
        public static string QuestionType {
            get {
                return ResourceManager.GetString("QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 根据规则自动添加.
        /// </summary>
        public static string Rule_Add {
            get {
                return ResourceManager.GetString("Rule Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试卷规则列表.
        /// </summary>
        public static string Rule_List {
            get {
                return ResourceManager.GetString("Rule List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分数.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择试卷规则.
        /// </summary>
        public static string Select_Rule {
            get {
                return ResourceManager.GetString("Select Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 课程.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 科目列表.
        /// </summary>
        public static string Subject_List {
            get {
                return ResourceManager.GetString("Subject List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交成功.
        /// </summary>
        public static string Submit_Success {
            get {
                return ResourceManager.GetString("Submit Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标题.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新时间.
        /// </summary>
        public static string Update_Time {
            get {
                return ResourceManager.GetString("Update Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户列表.
        /// </summary>
        public static string User_List {
            get {
                return ResourceManager.GetString("User List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户管理.
        /// </summary>
        public static string User_Management {
            get {
                return ResourceManager.GetString("User Management", resourceCulture);
            }
        }
    }
}
